name: Deploy LA demo app

on:
  push:
    branches:
      - main
    # paths:
    #  - LogicApp/**  # or wherever your logic app files are

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (required for Azure CLI extensions)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App Workflow
        run: |
          # Defined in Github Settings > Secrets and variables > Actions > Variables)
          RG_NAME=${{ vars.AZURE_LA_RG }}
          APP_NAME=${{ vars.AZURE_LA_NAME }}
          ZIP_PATH=${{ vars.AZURE_LA_APPFILES }}

          # Zip the logic app code (must contain workflow.json etc.)
          zip -r logicapp.zip $ZIP_PATH

          # Deploy using Azure CLI
          az functionapp deployment source config-zip \
            --resource-group $RG_NAME \
            --name $APP_NAME \
            --src logicapp.zip
