name: Deploy Logic App Standard

on:
  push:
    branches:
      - main
    # paths:
    #  - LogicApp/**  # or wherever your logic app files are

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (required for Azure CLI extensions)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App Workflow
        run: |
          # Variables (replace with your actual resource names)
          RG_NAME="cdk3-rg"
          APP_NAME="logicapp-win-std-cdk3"
          ZIP_PATH="."

          # Zip the logic app code (must contain workflow.json etc.)
          zip -r logicapp.zip $ZIP_PATH

          # Deploy using Azure CLI
          az functionapp deployment source config-zip \
            --resource-group $RG_NAME \
            --name $APP_NAME \
            --src logicapp.zip

      - name: Sync Logic App triggers
        run: |
          az functionapp sync-function-triggers \
            --name $APP_NAME \
            --resource-group $RG_NAME
      - name: Install Azure Logic extension
        run: |
          az extension add --name logic --yes || az extension update --name logic

      - name: Sync Logic App workflow triggers
        run: |
          az logic workflow sync \
            --resource-group $RG_NAME \
            --name Stateful1 \
            --app-name $APP_NAME
